apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
- namespace.yml
- deployment.yml
- service.yml
- ingress.yml

commonLabels:
  app: nginx

images:
- name: nginx
  newName: nginx
  newTag: 1.23.1
